export { default as Normal } from './png/Normal.png';
export { default as Fire } from './png/Fire.png';
export { default as Water } from './png/Water.png';
export { default as Electric } from './png/Electric.png';
export { default as Grass } from './png/Grass.png';
export { default as Ice } from './png/Ice.png';
export { default as Fighting } from './png/Fighting.png';
export { default as Poison } from './png/Poison.png';
export { default as Ground } from './png/Ground.png';
export { default as Flying } from './png/Flying.png';
export { default as Psychic } from './png/Psychic.png';
export { default as Bug } from './png/Bug.png';
export { default as Rock } from './png/Rock.png';
export { default as Ghost } from './png/Ghost.png';
export { default as Dragon } from './png/Dragon.png';
export { default as Dark } from './png/Dark.png';
export { default as Steel } from './png/Steel.png';
export { default as Fairy } from './png/Fairy.png';
export { default as Physical } from './png/Physical.png';
export { default as Special } from './png/Special.png';
export { default as Status } from './png/Status.png';
export { default as PhysicalStrike } from './png/Physical Strike.png';
export { default as SpecialStrike } from './png/Special Strike.png';
export { default as Support } from './png/Support.png';
export { default as Tech } from './png/Tech.png';
