import {
  shortenedMoveNameByAbilityIdDE,
  shortenedMoveNameByAbilityIdEN,
  shortenedMoveNameByAbilityIdIT,
  shortenedMoveNameByAbilityIdES,
  shortenedMoveNameByAbilityIdFR,
  shortenedMoveNameByAbilityIdKO,
  shortenedMoveNameByAbilityIdJA,
  shortenedMoveNameByAbilityIdZH,
  pikachuGridDataDE,
  torkoalGridDataDE,
  infernapeGridDataDE,
  dewgongGridDataDE,
  haxorusGridDataDE,
  kingdraGridDataDE,
  serperiorGridDataDE,
  vileplumeGridDataDE,
  mewGridDataDE,
  metagrossGridDataDE,
  charizardGridDataDE,
  palossandGridDataDE,
  liepardGridDataDE,
  rotomGridDataDE,
  houndoomGridDataDE,
  raichuGridDataDE,
  alakazamGridDataDE,
  helioliskGridDataDE,
  golisopodGridDataDE,
  salazzleGridDataDE,
  masquerainGridDataDE,
  meowsticGridDataDE,
  reuniclusGridDataDE,
  garchompGridDataDE,
  lucarioGridDataDE,
  swannaGridDataDE,
  galladeGridDataDE,
  miloticGridDataDE,
  steelixGridDataDE,
  starmieGridDataDE,
  pikachuGridDataEN,
  torkoalGridDataEN,
  infernapeGridDataEN,
  dewgongGridDataEN,
  haxorusGridDataEN,
  kingdraGridDataEN,
  serperiorGridDataEN,
  vileplumeGridDataEN,
  mewGridDataEN,
  metagrossGridDataEN,
  charizardGridDataEN,
  palossandGridDataEN,
  liepardGridDataEN,
  rotomGridDataEN,
  houndoomGridDataEN,
  raichuGridDataEN,
  alakazamGridDataEN,
  helioliskGridDataEN,
  golisopodGridDataEN,
  salazzleGridDataEN,
  masquerainGridDataEN,
  meowsticGridDataEN,
  reuniclusGridDataEN,
  garchompGridDataEN,
  lucarioGridDataEN,
  swannaGridDataEN,
  galladeGridDataEN,
  miloticGridDataEN,
  steelixGridDataEN,
  starmieGridDataEN,
  pikachuGridDataES,
  torkoalGridDataES,
  infernapeGridDataES,
  dewgongGridDataES,
  haxorusGridDataES,
  kingdraGridDataES,
  serperiorGridDataES,
  vileplumeGridDataES,
  mewGridDataES,
  metagrossGridDataES,
  charizardGridDataES,
  palossandGridDataES,
  liepardGridDataES,
  rotomGridDataES,
  houndoomGridDataES,
  raichuGridDataES,
  alakazamGridDataES,
  helioliskGridDataES,
  golisopodGridDataES,
  salazzleGridDataES,
  masquerainGridDataES,
  meowsticGridDataES,
  reuniclusGridDataES,
  garchompGridDataES,
  lucarioGridDataES,
  swannaGridDataES,
  galladeGridDataES,
  miloticGridDataES,
  steelixGridDataES,
  starmieGridDataES,
  pikachuGridDataFR,
  torkoalGridDataFR,
  infernapeGridDataFR,
  dewgongGridDataFR,
  haxorusGridDataFR,
  kingdraGridDataFR,
  serperiorGridDataFR,
  vileplumeGridDataFR,
  mewGridDataFR,
  metagrossGridDataFR,
  charizardGridDataFR,
  palossandGridDataFR,
  liepardGridDataFR,
  rotomGridDataFR,
  houndoomGridDataFR,
  raichuGridDataFR,
  alakazamGridDataFR,
  helioliskGridDataFR,
  golisopodGridDataFR,
  salazzleGridDataFR,
  masquerainGridDataFR,
  meowsticGridDataFR,
  reuniclusGridDataFR,
  garchompGridDataFR,
  lucarioGridDataFR,
  swannaGridDataFR,
  galladeGridDataFR,
  miloticGridDataFR,
  steelixGridDataFR,
  starmieGridDataFR,
  pikachuGridDataIT,
  torkoalGridDataIT,
  infernapeGridDataIT,
  dewgongGridDataIT,
  haxorusGridDataIT,
  kingdraGridDataIT,
  serperiorGridDataIT,
  vileplumeGridDataIT,
  mewGridDataIT,
  metagrossGridDataIT,
  charizardGridDataIT,
  palossandGridDataIT,
  liepardGridDataIT,
  rotomGridDataIT,
  houndoomGridDataIT,
  raichuGridDataIT,
  alakazamGridDataIT,
  helioliskGridDataIT,
  golisopodGridDataIT,
  salazzleGridDataIT,
  masquerainGridDataIT,
  meowsticGridDataIT,
  reuniclusGridDataIT,
  garchompGridDataIT,
  lucarioGridDataIT,
  swannaGridDataIT,
  galladeGridDataIT,
  miloticGridDataIT,
  steelixGridDataIT,
  starmieGridDataIT,
  pikachuGridDataJA,
  torkoalGridDataJA,
  infernapeGridDataJA,
  dewgongGridDataJA,
  haxorusGridDataJA,
  kingdraGridDataJA,
  serperiorGridDataJA,
  vileplumeGridDataJA,
  mewGridDataJA,
  metagrossGridDataJA,
  charizardGridDataJA,
  palossandGridDataJA,
  liepardGridDataJA,
  rotomGridDataJA,
  houndoomGridDataJA,
  raichuGridDataJA,
  alakazamGridDataJA,
  helioliskGridDataJA,
  golisopodGridDataJA,
  salazzleGridDataJA,
  masquerainGridDataJA,
  meowsticGridDataJA,
  reuniclusGridDataJA,
  garchompGridDataJA,
  lucarioGridDataJA,
  swannaGridDataJA,
  galladeGridDataJA,
  miloticGridDataJA,
  steelixGridDataJA,
  starmieGridDataJA,
  pikachuGridDataKO,
  torkoalGridDataKO,
  infernapeGridDataKO,
  dewgongGridDataKO,
  haxorusGridDataKO,
  kingdraGridDataKO,
  serperiorGridDataKO,
  vileplumeGridDataKO,
  mewGridDataKO,
  metagrossGridDataKO,
  charizardGridDataKO,
  palossandGridDataKO,
  liepardGridDataKO,
  rotomGridDataKO,
  houndoomGridDataKO,
  raichuGridDataKO,
  alakazamGridDataKO,
  helioliskGridDataKO,
  golisopodGridDataKO,
  salazzleGridDataKO,
  masquerainGridDataKO,
  meowsticGridDataKO,
  reuniclusGridDataKO,
  garchompGridDataKO,
  lucarioGridDataKO,
  swannaGridDataKO,
  galladeGridDataKO,
  miloticGridDataKO,
  steelixGridDataKO,
  starmieGridDataKO,
  pikachuGridDataZH,
  torkoalGridDataZH,
  infernapeGridDataZH,
  dewgongGridDataZH,
  haxorusGridDataZH,
  kingdraGridDataZH,
  serperiorGridDataZH,
  vileplumeGridDataZH,
  mewGridDataZH,
  metagrossGridDataZH,
  charizardGridDataZH,
  palossandGridDataZH,
  liepardGridDataZH,
  rotomGridDataZH,
  houndoomGridDataZH,
  raichuGridDataZH,
  alakazamGridDataZH,
  helioliskGridDataZH,
  golisopodGridDataZH,
  salazzleGridDataZH,
  masquerainGridDataZH,
  meowsticGridDataZH,
  reuniclusGridDataZH,
  garchompGridDataZH,
  lucarioGridDataZH,
  swannaGridDataZH,
  galladeGridDataZH,
  miloticGridDataZH,
  steelixGridDataZH,
  starmieGridDataZH,
  torterraGridDataDE,
  torterraGridDataEN,
  torterraGridDataES,
  torterraGridDataFR,
  torterraGridDataIT,
  torterraGridDataJA,
  torterraGridDataKO,
  torterraGridDataZH,
  sharpedoGridDataDE,
  sharpedoGridDataEN,
  sharpedoGridDataES,
  sharpedoGridDataFR,
  sharpedoGridDataIT,
  sharpedoGridDataJA,
  sharpedoGridDataKO,
  sharpedoGridDataZH,
  empoleonGridDataDE,
  empoleonGridDataEN,
  empoleonGridDataES,
  empoleonGridDataFR,
  empoleonGridDataIT,
  empoleonGridDataJA,
  empoleonGridDataKO,
  empoleonGridDataZH,
  leavannyGridDataDE,
  leavannyGridDataEN,
  leavannyGridDataES,
  leavannyGridDataFR,
  leavannyGridDataIT,
  leavannyGridDataJA,
  leavannyGridDataKO,
  leavannyGridDataZH,
  // 6/25/2020
  delphoxGridDataDE,
  emboarGridDataDE,
  drifblimGridDataDE,
  crobatGridDataDE,
  delphoxGridDataEN,
  emboarGridDataEN,
  drifblimGridDataEN,
  crobatGridDataEN,
  delphoxGridDataES,
  emboarGridDataES,
  drifblimGridDataES,
  crobatGridDataES,
  delphoxGridDataFR,
  emboarGridDataFR,
  drifblimGridDataFR,
  crobatGridDataFR,
  delphoxGridDataIT,
  emboarGridDataIT,
  drifblimGridDataIT,
  crobatGridDataIT,
  delphoxGridDataJA,
  emboarGridDataJA,
  drifblimGridDataJA,
  crobatGridDataJA,
  delphoxGridDataKO,
  emboarGridDataKO,
  drifblimGridDataKO,
  crobatGridDataKO,
  delphoxGridDataZH,
  emboarGridDataZH,
  drifblimGridDataZH,
  crobatGridDataZH,
  // 7/29/2020
  lycanrocGridDataDE,
  onixGridDataDE,
  sandslashGridDataDE,
  kommooGridDataDE,
  jigglypuffGridDataDE,
  dragoniteGridDataDE,
  lycanrocGridDataEN,
  onixGridDataEN,
  sandslashGridDataEN,
  kommooGridDataEN,
  jigglypuffGridDataEN,
  dragoniteGridDataEN,
  lycanrocGridDataES,
  onixGridDataES,
  sandslashGridDataES,
  kommooGridDataES,
  jigglypuffGridDataES,
  dragoniteGridDataES,
  lycanrocGridDataFR,
  onixGridDataFR,
  sandslashGridDataFR,
  kommooGridDataFR,
  jigglypuffGridDataFR,
  dragoniteGridDataFR,
  lycanrocGridDataIT,
  onixGridDataIT,
  sandslashGridDataIT,
  kommooGridDataIT,
  jigglypuffGridDataIT,
  dragoniteGridDataIT,
  lycanrocGridDataJA,
  onixGridDataJA,
  sandslashGridDataJA,
  kommooGridDataJA,
  jigglypuffGridDataJA,
  dragoniteGridDataJA,
  lycanrocGridDataKO,
  onixGridDataKO,
  sandslashGridDataKO,
  kommooGridDataKO,
  jigglypuffGridDataKO,
  dragoniteGridDataKO,
  lycanrocGridDataZH,
  onixGridDataZH,
  sandslashGridDataZH,
  kommooGridDataZH,
  jigglypuffGridDataZH,
  dragoniteGridDataZH,
  // 8/25/2020
  blastoiseGridDataDE,
  venusaurGridDataDE,
  feraligatrGridDataDE,
  typhlosionGridDataDE,
  meganiumGridDataDE,
  blastoiseGridDataEN,
  venusaurGridDataEN,
  feraligatrGridDataEN,
  typhlosionGridDataEN,
  meganiumGridDataEN,
  blastoiseGridDataES,
  venusaurGridDataES,
  feraligatrGridDataES,
  typhlosionGridDataES,
  meganiumGridDataES,
  blastoiseGridDataFR,
  venusaurGridDataFR,
  feraligatrGridDataFR,
  typhlosionGridDataFR,
  meganiumGridDataFR,
  blastoiseGridDataIT,
  venusaurGridDataIT,
  feraligatrGridDataIT,
  typhlosionGridDataIT,
  meganiumGridDataIT,
  blastoiseGridDataJA,
  venusaurGridDataJA,
  feraligatrGridDataJA,
  typhlosionGridDataJA,
  meganiumGridDataJA,
  blastoiseGridDataKO,
  venusaurGridDataKO,
  feraligatrGridDataKO,
  typhlosionGridDataKO,
  meganiumGridDataKO,
  blastoiseGridDataZH,
  venusaurGridDataZH,
  feraligatrGridDataZH,
  typhlosionGridDataZH,
  meganiumGridDataZH,
  // 9/7/2020
  clefairyGridDataDE,
  pheromosaGridDataDE,
  silvallyGridDataDE,
  clefairyGridDataEN,
  pheromosaGridDataEN,
  silvallyGridDataEN,
  clefairyGridDataES,
  pheromosaGridDataES,
  silvallyGridDataES,
  clefairyGridDataFR,
  pheromosaGridDataFR,
  silvallyGridDataFR,
  clefairyGridDataIT,
  pheromosaGridDataIT,
  silvallyGridDataIT,
  clefairyGridDataJA,
  pheromosaGridDataJA,
  silvallyGridDataJA,
  clefairyGridDataKO,
  pheromosaGridDataKO,
  silvallyGridDataKO,
  clefairyGridDataZH,
  pheromosaGridDataZH,
  silvallyGridDataZH,
  // 9/28/2020
  blastoise_newGridDataDE,
  mimikyuGridDataDE,
  mightyenaGridDataDE,
  zebstrikaGridDataDE,
  luxrayGridDataDE,
  mismagiusGridDataDE,
  glalieGridDataDE,
  blastoise_newGridDataEN,
  mimikyuGridDataEN,
  mightyenaGridDataEN,
  zebstrikaGridDataEN,
  luxrayGridDataEN,
  mismagiusGridDataEN,
  glalieGridDataEN,
  blastoise_newGridDataES,
  mimikyuGridDataES,
  mightyenaGridDataES,
  zebstrikaGridDataES,
  luxrayGridDataES,
  mismagiusGridDataES,
  glalieGridDataES,
  blastoise_newGridDataFR,
  mimikyuGridDataFR,
  mightyenaGridDataFR,
  zebstrikaGridDataFR,
  luxrayGridDataFR,
  mismagiusGridDataFR,
  glalieGridDataFR,
  blastoise_newGridDataIT,
  mimikyuGridDataIT,
  mightyenaGridDataIT,
  zebstrikaGridDataIT,
  luxrayGridDataIT,
  mismagiusGridDataIT,
  glalieGridDataIT,
  blastoise_newGridDataJA,
  mimikyuGridDataJA,
  mightyenaGridDataJA,
  zebstrikaGridDataJA,
  luxrayGridDataJA,
  mismagiusGridDataJA,
  glalieGridDataJA,
  blastoise_newGridDataKO,
  mimikyuGridDataKO,
  mightyenaGridDataKO,
  zebstrikaGridDataKO,
  luxrayGridDataKO,
  mismagiusGridDataKO,
  glalieGridDataKO,
  blastoise_newGridDataZH,
  mimikyuGridDataZH,
  mightyenaGridDataZH,
  zebstrikaGridDataZH,
  luxrayGridDataZH,
  mismagiusGridDataZH,
  glalieGridDataZH,
  // 10/28/2020
  olivia_lycanrocGridDataDE,
  altariaGridDataDE,
  braviaryGridDataDE,
  octilleryGridDataDE,
  pidgeotGridDataDE,
  musharnaGridDataDE,
  delibirdGridDataDE,
  olivia_lycanrocGridDataEN,
  altariaGridDataEN,
  braviaryGridDataEN,
  octilleryGridDataEN,
  pidgeotGridDataEN,
  musharnaGridDataEN,
  delibirdGridDataEN,
  olivia_lycanrocGridDataES,
  altariaGridDataES,
  braviaryGridDataES,
  octilleryGridDataES,
  pidgeotGridDataES,
  musharnaGridDataES,
  delibirdGridDataES,
  olivia_lycanrocGridDataFR,
  altariaGridDataFR,
  braviaryGridDataFR,
  octilleryGridDataFR,
  pidgeotGridDataFR,
  musharnaGridDataFR,
  delibirdGridDataFR,
  olivia_lycanrocGridDataIT,
  altariaGridDataIT,
  braviaryGridDataIT,
  octilleryGridDataIT,
  pidgeotGridDataIT,
  musharnaGridDataIT,
  delibirdGridDataIT,
  olivia_lycanrocGridDataJA,
  altariaGridDataJA,
  braviaryGridDataJA,
  octilleryGridDataJA,
  pidgeotGridDataJA,
  musharnaGridDataJA,
  delibirdGridDataJA,
  olivia_lycanrocGridDataKO,
  altariaGridDataKO,
  braviaryGridDataKO,
  octilleryGridDataKO,
  pidgeotGridDataKO,
  musharnaGridDataKO,
  delibirdGridDataKO,
  olivia_lycanrocGridDataZH,
  altariaGridDataZH,
  braviaryGridDataZH,
  octilleryGridDataZH,
  pidgeotGridDataZH,
  musharnaGridDataZH,
  delibirdGridDataZH,
  volcaronaGridDataDE,
  volcaronaGridDataEN,
  volcaronaGridDataES,
  volcaronaGridDataFR,
  volcaronaGridDataIT,
  volcaronaGridDataJA,
  volcaronaGridDataKO,
  volcaronaGridDataZH,
} from '../data';

import {
  // Pokemon 128px (grided)
  pm0006_00_lizardon_128, // Charizard
  pm0829_11_okami2noon_128, // Lycanroc
  pm0154_01_meganium_128, // Meganium
  pm0039_00_purin_128, // Jigglypuff
  pm0734_00_cat2_128, // Meowstic
  pm0500_00_enbuoh_128, // Emboar
  pm0392_00_goukazaru_128, // Infernape
  pm0823_00_sunaba2_128, // Palossand
  pm0045_01_ruffresia_128, // Vileplume
  pm0448_00_lucario_128, // Lucario
  pm0095_00_iwark_128, // Onix
  pm0581_00_swanna_128, // Swanna
  pm0133_00_eievui_128, // Eevee
  pm0003_01_fushigibana_128, // Venusaur
  pm0160_00_ordile_128, // Feraligatr
  pm0009_00_kamex_128, // Blastoise
  pm0230_00_kingdra_128, // Kingdra
  pm0324_00_cotoise_128, // Torkoal
  pm0087_00_jugon_128, // Dewgong
  pm0284_00_amemoth_128, // Masquerain
  pm0510_00_lepardas_128, // Liepard
  pm0319_00_samehader_128, // Sharpedo
  pm0169_00_crobat_128, // Crobat
  pm0229_01_hellgar_128, // Houndoom
  pm0376_00_metagross_128, // Metagross
  pm0028_61_asandpan_128, // Sandslash
  pm0445_01_gaburias_128, // Garchomp
  pm0818_00_uroko3_128, //Kommo-o
  pm0612_00_ononokus_128, // Haxorus
  pm0579_00_lanculus_128, // Reuniclus
  pm0025_00_pikachu_128, // Pikachu
  pm0026_61_araichu_128, // Raichu
  pm0395_00_emperte_128, // Empoleon
  pm0497_00_jalorda_128, // Serperior
  pm0523_00_zebraika_128, // Zebstrika
  pm0479_11_rotom_128, // Rotom
  pm0121_00_starmie_128, // Starmie
  pm0149_00_kairyu_128, // Dragonite
  pm0157_00_bakphoon_128, // Typhlosion
  pm0208_01_haganeil_128, // Steelix
  pm0065_00_foodin_128, // Alakazam
  pm0389_00_dodaitose_128, // Torterra
  pm0035_00_pippi_128, // Clefairy
  pm0862_11_gryps2_128, // Silvally
  pm0879_00_beastblue_128, // Pheromosa
  pm0806_00_dokutokage2_128, // Salazzle
  pm0867_00_gusokumushi2_128, // Golisopod
  pm0350_01_milokaross_128, // Milotic
  pm0475_00_erureido_128, // Gallade
  pm0719_00_fox3_128, // Delphox
  pm0732_00_frilledlizard2_128, // Heliolisk
  pm0151_00_mew_128, // Mew
  pm0426_00_fuwaride_128, // Drifblim
  pm0429_00_mumargi_128, // Mismagius
  pm0362_00_onigohri_128, // Glalie
  pm0542_00_hahakomori_128, // Leavanny

  // 9/28/2020
  pm0819_11_horror_128, // Mimikyu
  pm0262_00_graena_128, // Mightyena
  pm0405_00_rentorar_128, // Luxray

  // 10/28/2020
  pm0018_00_pigeot_128, // Pidgeot
  pm0225_00_delibird_128, // Delibird
  pm0829_12_okami2night_128, // Lycanroc_midnight
  pm0628_00_warrgle_128, // Braviary
  pm0518_00_musharna_128, // Musharna
  pm0334_00_tyltalis_128, // Altaria
  pm0224_00_okutank_128, // Octillery

  // 11/4/2020
  pm0637_00_ulgamoth_128, // Volcarona
} from '../images/Pokemon';

export const pokemonPictures = {
  // Pokemon 128px
  pm0006_00_lizardon_128, // Charizard
  pm0829_11_okami2noon_128, // Lycanroc
  pm0154_01_meganium_128, // Meganium
  pm0039_00_purin_128, // Jigglypuff
  pm0734_00_cat2_128, // Meowstic
  pm0500_00_enbuoh_128, // Emboar
  pm0392_00_goukazaru_128, // Infernape
  pm0823_00_sunaba2_128, // Palossand
  pm0045_01_ruffresia_128, // Vileplume
  pm0448_00_lucario_128, // Lucario
  pm0095_00_iwark_128, // Onix
  pm0581_00_swanna_128, // Swanna
  pm0133_00_eievui_128, // Eevee
  pm0003_01_fushigibana_128, // Venusaur
  pm0160_00_ordile_128, // Feraligatr
  pm0009_00_kamex_128, // Blastoise
  pm0230_00_kingdra_128, // Kingdra
  pm0324_00_cotoise_128, // Torkoal
  pm0087_00_jugon_128, // Dewgong
  pm0284_00_amemoth_128, // Masquerain
  pm0510_00_lepardas_128, // Liepard
  pm0319_00_samehader_128, // Sharpedo
  pm0169_00_crobat_128, // Crobat
  pm0229_01_hellgar_128, // Houndoom
  pm0376_00_metagross_128, // Metagross
  pm0028_61_asandpan_128, // Sandslash
  pm0445_01_gaburias_128, // Garchomp
  pm0818_00_uroko3_128, //Kommo-o
  pm0612_00_ononokus_128, // Haxorus
  pm0579_00_lanculus_128, // Reuniclus
  pm0025_00_pikachu_128, // Pikachu
  pm0026_61_araichu_128, // Raichu
  pm0395_00_emperte_128, // Empoleon
  pm0497_00_jalorda_128, // Serperior
  pm0523_00_zebraika_128, // Zebstrika
  pm0479_11_rotom_128, // Rotom
  pm0121_00_starmie_128, // Starmie
  pm0149_00_kairyu_128, // Dragonite
  pm0157_00_bakphoon_128, // Typhlosion
  pm0208_01_haganeil_128, // Steelix
  pm0065_00_foodin_128, // Alakazam
  pm0389_00_dodaitose_128, // Torterra
  pm0035_00_pippi_128, // Clefairy
  pm0862_11_gryps2_128, // Silvally
  pm0879_00_beastblue_128, // Pheromosa
  pm0806_00_dokutokage2_128, // Salazzle
  pm0867_00_gusokumushi2_128, // Golisopod
  pm0350_01_milokaross_128, // Milotic
  pm0475_00_erureido_128, // Gallade
  pm0719_00_fox3_128, // Delphox
  pm0732_00_frilledlizard2_128, // Heliolisk
  pm0151_00_mew_128, // Mew
  pm0426_00_fuwaride_128, // Drifblim
  pm0429_00_mumargi_128, // Mismagius
  pm0362_00_onigohri_128, // Glalie
  pm0542_00_hahakomori_128, // Leavanny

  // 9/28/2020
  pm0819_11_horror_128, // Mimikyu
  pm0262_00_graena_128, // Mightyena
  pm0405_00_rentorar_128, // Luxray

  // 10/28/2020
  pm0018_00_pigeot_128, // Pidgeot
  pm0225_00_delibird_128, // Delibird
  pm0829_12_okami2night_128, // Lycanroc_midnight
  pm0628_00_warrgle_128, // Braviary
  pm0518_00_musharna_128, // Musharna
  pm0334_00_tyltalis_128, // Altaria
  pm0224_00_okutank_128, // Octillery

  // 11/4/2020
  pm0637_00_ulgamoth_128, // Volcarona
};

export const shortenedMoveNameByAbilityId = {
  de: shortenedMoveNameByAbilityIdDE,
  en: shortenedMoveNameByAbilityIdEN,
  it: shortenedMoveNameByAbilityIdIT,
  es: shortenedMoveNameByAbilityIdES,
  fr: shortenedMoveNameByAbilityIdFR,
  ko: shortenedMoveNameByAbilityIdKO,
  ja: shortenedMoveNameByAbilityIdJA,
  zh: shortenedMoveNameByAbilityIdZH,
};

export const allSyncGrids = {
  de: {
    pikachuGridDataDE,
    torkoalGridDataDE,
    infernapeGridDataDE,
    dewgongGridDataDE,
    haxorusGridDataDE,
    kingdraGridDataDE,
    serperiorGridDataDE,
    vileplumeGridDataDE,
    mewGridDataDE,
    metagrossGridDataDE,
    charizardGridDataDE,
    palossandGridDataDE,
    liepardGridDataDE,
    rotomGridDataDE,
    houndoomGridDataDE,
    raichuGridDataDE,
    alakazamGridDataDE,
    helioliskGridDataDE,
    golisopodGridDataDE,
    salazzleGridDataDE,
    masquerainGridDataDE,
    meowsticGridDataDE,
    reuniclusGridDataDE,
    garchompGridDataDE,
    lucarioGridDataDE,
    swannaGridDataDE,
    galladeGridDataDE,
    miloticGridDataDE,
    steelixGridDataDE,
    starmieGridDataDE,
    torterraGridDataDE,
    sharpedoGridDataDE,
    empoleonGridDataDE,
    leavannyGridDataDE,
    delphoxGridDataDE,
    emboarGridDataDE,
    drifblimGridDataDE,
    crobatGridDataDE,
    lycanrocGridDataDE,
    onixGridDataDE,
    sandslashGridDataDE,
    kommooGridDataDE,
    jigglypuffGridDataDE,
    dragoniteGridDataDE,
    blastoiseGridDataDE,
    venusaurGridDataDE,
    feraligatrGridDataDE,
    typhlosionGridDataDE,
    meganiumGridDataDE,
    clefairyGridDataDE,
    pheromosaGridDataDE,
    silvallyGridDataDE,
    blastoise_newGridDataDE,
    mimikyuGridDataDE,
    mightyenaGridDataDE,
    zebstrikaGridDataDE,
    luxrayGridDataDE,
    mismagiusGridDataDE,
    glalieGridDataDE,
    olivia_lycanrocGridDataDE,
    altariaGridDataDE,
    braviaryGridDataDE,
    octilleryGridDataDE,
    pidgeotGridDataDE,
    musharnaGridDataDE,
    delibirdGridDataDE,
    volcaronaGridDataDE,
  },
  en: {
    pikachuGridDataEN,
    torkoalGridDataEN,
    infernapeGridDataEN,
    dewgongGridDataEN,
    haxorusGridDataEN,
    kingdraGridDataEN,
    serperiorGridDataEN,
    vileplumeGridDataEN,
    mewGridDataEN,
    charizardGridDataEN,
    metagrossGridDataEN,
    palossandGridDataEN,
    liepardGridDataEN,
    rotomGridDataEN,
    houndoomGridDataEN,
    raichuGridDataEN,
    alakazamGridDataEN,
    helioliskGridDataEN,
    golisopodGridDataEN,
    salazzleGridDataEN,
    masquerainGridDataEN,
    meowsticGridDataEN,
    reuniclusGridDataEN,
    garchompGridDataEN,
    lucarioGridDataEN,
    swannaGridDataEN,
    galladeGridDataEN,
    miloticGridDataEN,
    steelixGridDataEN,
    starmieGridDataEN,
    torterraGridDataEN,
    sharpedoGridDataEN,
    empoleonGridDataEN,
    leavannyGridDataEN,
    delphoxGridDataEN,
    emboarGridDataEN,
    drifblimGridDataEN,
    crobatGridDataEN,
    lycanrocGridDataEN,
    onixGridDataEN,
    sandslashGridDataEN,
    kommooGridDataEN,
    jigglypuffGridDataEN,
    dragoniteGridDataEN,
    blastoiseGridDataEN,
    venusaurGridDataEN,
    feraligatrGridDataEN,
    typhlosionGridDataEN,
    meganiumGridDataEN,
    clefairyGridDataEN,
    pheromosaGridDataEN,
    silvallyGridDataEN,
    blastoise_newGridDataEN,
    mimikyuGridDataEN,
    mightyenaGridDataEN,
    zebstrikaGridDataEN,
    luxrayGridDataEN,
    mismagiusGridDataEN,
    glalieGridDataEN,
    olivia_lycanrocGridDataEN,
    altariaGridDataEN,
    braviaryGridDataEN,
    octilleryGridDataEN,
    pidgeotGridDataEN,
    musharnaGridDataEN,
    delibirdGridDataEN,
    volcaronaGridDataEN,
  },
  es: {
    pikachuGridDataES,
    torkoalGridDataES,
    infernapeGridDataES,
    dewgongGridDataES,
    haxorusGridDataES,
    kingdraGridDataES,
    serperiorGridDataES,
    vileplumeGridDataES,
    mewGridDataES,
    metagrossGridDataES,
    charizardGridDataES,
    palossandGridDataES,
    liepardGridDataES,
    rotomGridDataES,
    houndoomGridDataES,
    raichuGridDataES,
    alakazamGridDataES,
    helioliskGridDataES,
    golisopodGridDataES,
    salazzleGridDataES,
    masquerainGridDataES,
    meowsticGridDataES,
    reuniclusGridDataES,
    garchompGridDataES,
    lucarioGridDataES,
    swannaGridDataES,
    galladeGridDataES,
    miloticGridDataES,
    steelixGridDataES,
    starmieGridDataES,
    torterraGridDataES,
    sharpedoGridDataES,
    empoleonGridDataES,
    leavannyGridDataES,
    delphoxGridDataES,
    emboarGridDataES,
    drifblimGridDataES,
    crobatGridDataES,
    lycanrocGridDataES,
    onixGridDataES,
    sandslashGridDataES,
    kommooGridDataES,
    jigglypuffGridDataES,
    dragoniteGridDataES,
    blastoiseGridDataES,
    venusaurGridDataES,
    feraligatrGridDataES,
    typhlosionGridDataES,
    meganiumGridDataES,
    clefairyGridDataES,
    pheromosaGridDataES,
    silvallyGridDataES,
    blastoise_newGridDataES,
    mimikyuGridDataES,
    mightyenaGridDataES,
    zebstrikaGridDataES,
    luxrayGridDataES,
    mismagiusGridDataES,
    glalieGridDataES,
    olivia_lycanrocGridDataES,
    altariaGridDataES,
    braviaryGridDataES,
    octilleryGridDataES,
    pidgeotGridDataES,
    musharnaGridDataES,
    delibirdGridDataES,
    volcaronaGridDataES,
  },
  fr: {
    pikachuGridDataFR,
    torkoalGridDataFR,
    infernapeGridDataFR,
    dewgongGridDataFR,
    haxorusGridDataFR,
    kingdraGridDataFR,
    serperiorGridDataFR,
    vileplumeGridDataFR,
    mewGridDataFR,
    metagrossGridDataFR,
    charizardGridDataFR,
    palossandGridDataFR,
    liepardGridDataFR,
    rotomGridDataFR,
    houndoomGridDataFR,
    raichuGridDataFR,
    alakazamGridDataFR,
    helioliskGridDataFR,
    golisopodGridDataFR,
    salazzleGridDataFR,
    masquerainGridDataFR,
    meowsticGridDataFR,
    reuniclusGridDataFR,
    garchompGridDataFR,
    lucarioGridDataFR,
    swannaGridDataFR,
    galladeGridDataFR,
    miloticGridDataFR,
    steelixGridDataFR,
    starmieGridDataFR,
    torterraGridDataFR,
    sharpedoGridDataFR,
    empoleonGridDataFR,
    leavannyGridDataFR,
    delphoxGridDataFR,
    emboarGridDataFR,
    drifblimGridDataFR,
    crobatGridDataFR,
    lycanrocGridDataFR,
    onixGridDataFR,
    sandslashGridDataFR,
    kommooGridDataFR,
    jigglypuffGridDataFR,
    dragoniteGridDataFR,
    blastoiseGridDataFR,
    venusaurGridDataFR,
    feraligatrGridDataFR,
    typhlosionGridDataFR,
    meganiumGridDataFR,
    clefairyGridDataFR,
    pheromosaGridDataFR,
    silvallyGridDataFR,
    blastoise_newGridDataFR,
    mimikyuGridDataFR,
    mightyenaGridDataFR,
    zebstrikaGridDataFR,
    luxrayGridDataFR,
    mismagiusGridDataFR,
    glalieGridDataFR,
    olivia_lycanrocGridDataFR,
    altariaGridDataFR,
    braviaryGridDataFR,
    octilleryGridDataFR,
    pidgeotGridDataFR,
    musharnaGridDataFR,
    delibirdGridDataFR,
    volcaronaGridDataFR,
  },
  it: {
    pikachuGridDataIT,
    torkoalGridDataIT,
    infernapeGridDataIT,
    dewgongGridDataIT,
    haxorusGridDataIT,
    kingdraGridDataIT,
    serperiorGridDataIT,
    vileplumeGridDataIT,
    mewGridDataIT,
    metagrossGridDataIT,
    charizardGridDataIT,
    palossandGridDataIT,
    liepardGridDataIT,
    rotomGridDataIT,
    houndoomGridDataIT,
    raichuGridDataIT,
    alakazamGridDataIT,
    helioliskGridDataIT,
    golisopodGridDataIT,
    salazzleGridDataIT,
    masquerainGridDataIT,
    meowsticGridDataIT,
    reuniclusGridDataIT,
    garchompGridDataIT,
    lucarioGridDataIT,
    swannaGridDataIT,
    galladeGridDataIT,
    miloticGridDataIT,
    steelixGridDataIT,
    starmieGridDataIT,
    torterraGridDataIT,
    sharpedoGridDataIT,
    empoleonGridDataIT,
    leavannyGridDataIT,
    delphoxGridDataIT,
    emboarGridDataIT,
    drifblimGridDataIT,
    crobatGridDataIT,
    lycanrocGridDataIT,
    onixGridDataIT,
    sandslashGridDataIT,
    kommooGridDataIT,
    jigglypuffGridDataIT,
    dragoniteGridDataIT,
    blastoiseGridDataIT,
    venusaurGridDataIT,
    feraligatrGridDataIT,
    typhlosionGridDataIT,
    meganiumGridDataIT,
    clefairyGridDataIT,
    pheromosaGridDataIT,
    silvallyGridDataIT,
    blastoise_newGridDataIT,
    mimikyuGridDataIT,
    mightyenaGridDataIT,
    zebstrikaGridDataIT,
    luxrayGridDataIT,
    mismagiusGridDataIT,
    glalieGridDataIT,
    olivia_lycanrocGridDataIT,
    altariaGridDataIT,
    braviaryGridDataIT,
    octilleryGridDataIT,
    pidgeotGridDataIT,
    musharnaGridDataIT,
    delibirdGridDataIT,
    volcaronaGridDataIT,
  },
  ja: {
    pikachuGridDataJA,
    torkoalGridDataJA,
    infernapeGridDataJA,
    dewgongGridDataJA,
    haxorusGridDataJA,
    kingdraGridDataJA,
    serperiorGridDataJA,
    vileplumeGridDataJA,
    mewGridDataJA,
    metagrossGridDataJA,
    charizardGridDataJA,
    palossandGridDataJA,
    liepardGridDataJA,
    rotomGridDataJA,
    houndoomGridDataJA,
    raichuGridDataJA,
    alakazamGridDataJA,
    helioliskGridDataJA,
    golisopodGridDataJA,
    salazzleGridDataJA,
    masquerainGridDataJA,
    meowsticGridDataJA,
    reuniclusGridDataJA,
    garchompGridDataJA,
    lucarioGridDataJA,
    swannaGridDataJA,
    galladeGridDataJA,
    miloticGridDataJA,
    steelixGridDataJA,
    starmieGridDataJA,
    torterraGridDataJA,
    sharpedoGridDataJA,
    empoleonGridDataJA,
    leavannyGridDataJA,
    delphoxGridDataJA,
    emboarGridDataJA,
    drifblimGridDataJA,
    crobatGridDataJA,
    lycanrocGridDataJA,
    onixGridDataJA,
    sandslashGridDataJA,
    kommooGridDataJA,
    jigglypuffGridDataJA,
    dragoniteGridDataJA,
    blastoiseGridDataJA,
    venusaurGridDataJA,
    feraligatrGridDataJA,
    typhlosionGridDataJA,
    meganiumGridDataJA,
    clefairyGridDataJA,
    pheromosaGridDataJA,
    silvallyGridDataJA,
    blastoise_newGridDataJA,
    mimikyuGridDataJA,
    mightyenaGridDataJA,
    zebstrikaGridDataJA,
    luxrayGridDataJA,
    mismagiusGridDataJA,
    glalieGridDataJA,
    olivia_lycanrocGridDataJA,
    altariaGridDataJA,
    braviaryGridDataJA,
    octilleryGridDataJA,
    pidgeotGridDataJA,
    musharnaGridDataJA,
    delibirdGridDataJA,
    volcaronaGridDataJA,
  },
  ko: {
    pikachuGridDataKO,
    torkoalGridDataKO,
    infernapeGridDataKO,
    dewgongGridDataKO,
    haxorusGridDataKO,
    kingdraGridDataKO,
    serperiorGridDataKO,
    vileplumeGridDataKO,
    mewGridDataKO,
    metagrossGridDataKO,
    charizardGridDataKO,
    palossandGridDataKO,
    liepardGridDataKO,
    rotomGridDataKO,
    houndoomGridDataKO,
    raichuGridDataKO,
    alakazamGridDataKO,
    helioliskGridDataKO,
    golisopodGridDataKO,
    salazzleGridDataKO,
    masquerainGridDataKO,
    meowsticGridDataKO,
    reuniclusGridDataKO,
    garchompGridDataKO,
    lucarioGridDataKO,
    swannaGridDataKO,
    galladeGridDataKO,
    miloticGridDataKO,
    steelixGridDataKO,
    starmieGridDataKO,
    torterraGridDataKO,
    sharpedoGridDataKO,
    empoleonGridDataKO,
    leavannyGridDataKO,
    delphoxGridDataKO,
    emboarGridDataKO,
    drifblimGridDataKO,
    crobatGridDataKO,
    lycanrocGridDataKO,
    onixGridDataKO,
    sandslashGridDataKO,
    kommooGridDataKO,
    jigglypuffGridDataKO,
    dragoniteGridDataKO,
    blastoiseGridDataKO,
    venusaurGridDataKO,
    feraligatrGridDataKO,
    typhlosionGridDataKO,
    meganiumGridDataKO,
    clefairyGridDataKO,
    pheromosaGridDataKO,
    silvallyGridDataKO,
    blastoise_newGridDataKO,
    mimikyuGridDataKO,
    mightyenaGridDataKO,
    zebstrikaGridDataKO,
    luxrayGridDataKO,
    mismagiusGridDataKO,
    glalieGridDataKO,
    olivia_lycanrocGridDataKO,
    altariaGridDataKO,
    braviaryGridDataKO,
    octilleryGridDataKO,
    pidgeotGridDataKO,
    musharnaGridDataKO,
    delibirdGridDataKO,
    volcaronaGridDataKO,
  },
  zh: {
    pikachuGridDataZH,
    torkoalGridDataZH,
    infernapeGridDataZH,
    dewgongGridDataZH,
    haxorusGridDataZH,
    kingdraGridDataZH,
    serperiorGridDataZH,
    vileplumeGridDataZH,
    mewGridDataZH,
    metagrossGridDataZH,
    charizardGridDataZH,
    palossandGridDataZH,
    liepardGridDataZH,
    rotomGridDataZH,
    houndoomGridDataZH,
    raichuGridDataZH,
    alakazamGridDataZH,
    helioliskGridDataZH,
    golisopodGridDataZH,
    salazzleGridDataZH,
    masquerainGridDataZH,
    meowsticGridDataZH,
    reuniclusGridDataZH,
    garchompGridDataZH,
    lucarioGridDataZH,
    swannaGridDataZH,
    galladeGridDataZH,
    miloticGridDataZH,
    steelixGridDataZH,
    starmieGridDataZH,
    torterraGridDataZH,
    sharpedoGridDataZH,
    empoleonGridDataZH,
    leavannyGridDataZH,
    delphoxGridDataZH,
    emboarGridDataZH,
    drifblimGridDataZH,
    crobatGridDataZH,
    olivia_lycanrocGridDataZH,
    onixGridDataZH,
    sandslashGridDataZH,
    kommooGridDataZH,
    jigglypuffGridDataZH,
    dragoniteGridDataZH,
    blastoiseGridDataZH,
    venusaurGridDataZH,
    feraligatrGridDataZH,
    typhlosionGridDataZH,
    meganiumGridDataZH,
    clefairyGridDataZH,
    pheromosaGridDataZH,
    silvallyGridDataZH,
    blastoise_newGridDataZH,
    mimikyuGridDataZH,
    mightyenaGridDataZH,
    zebstrikaGridDataZH,
    luxrayGridDataZH,
    mismagiusGridDataZH,
    glalieGridDataZH,
    lycanrocGridDataZH,
    altariaGridDataZH,
    braviaryGridDataZH,
    octilleryGridDataZH,
    pidgeotGridDataZH,
    musharnaGridDataZH,
    delibirdGridDataZH,
    volcaronaGridDataZH,
  },
};

export const UA_ID = 'UA-157426792-1';

export const DRAWER_WIDTH = 240;
